using System;
using System.Collections.Generic;

namespace ExtensionSugar
{
    public enum enTimeZone
    {
        DatelineStandardTime = 0,
        UTC11 = 1,
        AleutianStandardTime = 2,
        HawaiianStandardTime = 3,
        MarquesasStandardTime = 4,
        AlaskanStandardTime = 5,
        UTC09 = 6,
        PacificStandardTimeMexico = 7,
        UTC08 = 8,
        PacificStandard_Time = 9,
        USMountainStandardTime =10,
        MountainStandardTimeMexico =11,
        MountainStandardTime = 12,
        CentralStandardTimeMexico = 13,
        CentralStandardTime = 14,
        CentralAmericaStandardTime = 15,
        EasterIslandStandardTime = 16,
        CanadaCentralStandardTime = 17,
        SAPacificStandardTime = 18,
        EasternStandardTimeMexico = 19,
        EasternStandardTime = 20,
        HaitiStandardTime = 21,
        CubaStandardTime = 22,
        USEasternStandardTime = 23,
        TurksAndCaicosStandardTime = 24,
        ParaguayStandardTime = 25,
        AtlanticStandardTime = 26,
        CentralBrazilianStandardTime = 27,
        SAWesternStandardTime = 28,
        VenezuelaStandardTime = 29,
        PacificSAStandardTime = 30,
        NewfoundlandStandardTime = 31,
        TocantinsStandardTime = 32,
        ESouthAmericaStandardTime = 33,
        ArgentinaStandardTime = 34,
        SAEasternStandardTime = 35,
        GreenlandStandardTime = 36,
        MontevideoStandardTime = 37,
        MagallanesStandardTime = 38,
        SaintPierreStandardTime = 39,
        BahiaStandardTime = 40,
        UTC02 = 41,
        MidAtlanticStandardTime = 42,
        AzoresStandardTime = 43,
        CapeVerdeStandardTime = 44,
        UTC = 45,
        GMTStandardTime = 46,
        GreenwichStandardTime = 47,
        SaoTomeStandardTime = 48,
        MoroccoStandardTime = 49,
        WEuropeStandardTime = 50,
        CentralEuropeStandardTime = 51,
        RomanceStandardTime = 52,
        WCentralAfricaStandardTime = 53,
        CentralEuropeanStandardTime = 54,
        JordanStandardTime = 55,
        GTBStandardTime = 56,
        MiddleEastStandardTime = 57,
        EEuropeStandardTime = 58,
        WestBankStandardTime = 59,
        SouthAfricaStandardTime = 60,
        SudanStandardTime = 61,
        FLEStandardTime = 62,
        EgyptStandardTime = 63,
        KaliningradStandardTime = 64,
        IsraelStandardTime = 65,
        LibyaStandardTime = 66,
        NamibiaStandardTime = 67,
        SyriaStandardTime = 68,
        ArabicStandardTime = 69,
        ArabStandardTime = 70,
        BelarusStandardTime = 71,
        RussianStandardTime = 72,
        EAfricaStandardTime = 73,
        TurkeyStandardTime = 74,
        IranStandardTime = 75,
        ArabianStandardTime = 76,
        AstrakhanStandardTime = 77,
        AzerbaijanStandardTime = 78,
        CaucasusStandardTime = 79,
        MauritiusStandardTime = 80,
        SaratovStandardTime = 81,
        GeorgianStandardTime = 82,
        VolgogradStandardTime = 83,
        RussiaTimeZone3 = 84,
        AfghanistanStandardTime = 85,
        WestAsiaStandardTime = 86,
        QyzylordaStandardTime = 87,
        EkaterinburgStandardTime = 88,
        PakistanStandardTime = 89,
        IndiaStandardTime = 90,
        SriLankaStandardTime = 91,
        NepalStandardTime = 92,
        CentralAsiaStandardTime = 93,
        BangladeshStandardTime = 94,
        OmskStandardTime = 95,
        MyanmarStandardTime = 96,
        SEAsiaStandardTime = 97,
        AltaiStandardTime = 98,
        WMongoliaStandardTime = 99,
        NorthAsiaStandardTime = 100,
        NCentralAsiaStandardTime = 101,
        TomskStandardTime = 102,
        SingaporeStandardTime = 103,
        ChinaStandardTime = 104,
        WAustraliaStandardTime = 105,
        TaipeiStandardTime = 106,
        UlaanbaatarStandardTime = 107,
        NorthAsiaEastStandardTime = 108,
        AusCentralWStandardTime = 109,
        TransbaikalStandardTime = 110,
        TokyoStandardTime = 111,
        NorthKoreaStandardTime = 112,
        KoreaStandardTime = 113,
        YakutskStandardTime = 114,
        CenAustraliaStandardTime = 115,
        AUSCentralStandardTime = 116,
        EAustraliaStandardTime = 117,
        WestPacificStandardTime = 118,
        TasmaniaStandardTime = 119,
        AUSEasternStandardTime = 120,
        VladivostokStandardTime = 121,
        LordHoweStandardTime = 122,
        BougainvilleStandardTime = 123,
        MagadanStandardTime = 124,
        NorfolkStandardTime = 125,
        SakhalinStandardTime = 126,
        CentralPacificStandardTime = 127,
        RussiaTimeZone10 = 128,
        RussiaTimeZone11 = 129,
        NewZealandStandardTime = 130,
        UTC12 = 131,
        FijiStandardTime = 132,
        KamchatkaStandardTime = 133,
        ChathamIslandsStandardTime = 134,
        UTC13 = 135,
        TongaStandardTime = 136,
        SamoaStandardTime = 137,
        LineIslandsStandardTime = 138,
    }

    public static class DateTimeExtSugars
    {
        private static Dictionary<enTimeZone, string> ZoneIdName = new Dictionary<enTimeZone, string>()
        {
            {enTimeZone.DatelineStandardTime ,"Dateline Standard Time"},
            {enTimeZone.UTC11 ,"UTC-11"},
            {enTimeZone.AleutianStandardTime ,"Aleutian Standard Time"},
            {enTimeZone.HawaiianStandardTime ,"Hawaiian Standard Time"},
            {enTimeZone.MarquesasStandardTime ,"Marquesas Standard Time"},
            {enTimeZone.AlaskanStandardTime ,"Alaskan Standard Time"},
            {enTimeZone.UTC09 ,"UTC-09"},
            {enTimeZone.PacificStandardTimeMexico ,"Pacific Standard Time (Mexico)"},
            {enTimeZone.UTC08 ,"UTC-08"},
            {enTimeZone.PacificStandard_Time ,"Pacific Standard Time"},
            {enTimeZone.USMountainStandardTime ,"US Mountain Standard Time"},
            {enTimeZone.MountainStandardTimeMexico ,"Mountain Standard Time (Mexico)"},
            {enTimeZone.MountainStandardTime ,"Mountain Standard Time"},
            {enTimeZone.CentralStandardTimeMexico ,"Central Standard Time (Mexico)"},
            {enTimeZone.CentralStandardTime ,"Central Standard Time"},
            {enTimeZone.CentralAmericaStandardTime ,"Central America Standard Time"},
            {enTimeZone.EasterIslandStandardTime ,"Easter Island Standard Time"},
            {enTimeZone.CanadaCentralStandardTime ,"Canada Central Standard Time"},
            {enTimeZone.SAPacificStandardTime ,"SA Pacific Standard Time"},
            {enTimeZone.EasternStandardTimeMexico ,"Eastern Standard Time (Mexico)"},
            {enTimeZone.EasternStandardTime ,"Eastern Standard Time"},
            {enTimeZone.HaitiStandardTime ,"Haiti Standard Time"},
            {enTimeZone.CubaStandardTime ,"Cuba Standard Time"},
            {enTimeZone.USEasternStandardTime,"US Eastern Standard Time"},
            {enTimeZone.TurksAndCaicosStandardTime ,"Turks And Caicos Standard Time"},
            {enTimeZone.ParaguayStandardTime ,"Paraguay Standard Time"},
            {enTimeZone.AtlanticStandardTime ,"Atlantic Standard Time"},
            {enTimeZone.CentralBrazilianStandardTime ,"Central Brazilian Standard Time"},
            {enTimeZone.SAWesternStandardTime ,"SA Western Standard Time"},
            {enTimeZone.VenezuelaStandardTime ,"Venezuela Standard Time"},
            {enTimeZone.PacificSAStandardTime ,"Pacific SA Standard Time"},
            {enTimeZone.NewfoundlandStandardTime,"Newfoundland Standard Time"},
            {enTimeZone.TocantinsStandardTime ,"Tocantins Standard Time"},
            {enTimeZone.ESouthAmericaStandardTime ,"E. South America Standard Time"},
            {enTimeZone.ArgentinaStandardTime ,"Argentina Standard Time"},
            {enTimeZone.SAEasternStandardTime ,"SA Eastern Standard Time"},
            {enTimeZone.GreenlandStandardTime ,"Greenland Standard Time"},
            {enTimeZone.MontevideoStandardTime ,"Montevideo Standard Time"},
            {enTimeZone.MagallanesStandardTime ,"Magallanes Standard Time"},
            {enTimeZone.SaintPierreStandardTime,"Saint Pierre Standard Time"},
            {enTimeZone.BahiaStandardTime ,"Bahia Standard Time"},
            {enTimeZone.UTC02 ,"UTC-02"},
            {enTimeZone.MidAtlanticStandardTime ,"Mid-Atlantic Standard Time"},
            {enTimeZone.AzoresStandardTime,"Azores Standard Time"},
            {enTimeZone.CapeVerdeStandardTime ,"Cape Verde Standard Time"},
            {enTimeZone.UTC ,"UTC"},
            {enTimeZone.GMTStandardTime ,"GMT Standard Time"},
            {enTimeZone.GreenwichStandardTime ,"Greenwich Standard Time"},
            {enTimeZone.SaoTomeStandardTime ,"Sao Tome Standard Time"},
            {enTimeZone.MoroccoStandardTime ,"Morocco Standard Time"},
            {enTimeZone.WEuropeStandardTime ,"W. Europe Standard Time"},
            {enTimeZone.CentralEuropeStandardTime ,"Central Europe Standard Time"},
            {enTimeZone.RomanceStandardTime ,"Romance Standard Time"},
            {enTimeZone.WCentralAfricaStandardTime ,"W. Central Africa Standard Time"},
            {enTimeZone.CentralEuropeanStandardTime ,"Central European Standard Time"},
            {enTimeZone.JordanStandardTime ,"Jordan Standard Time"},
            {enTimeZone.GTBStandardTime ,"GTB Standard Time"},
            {enTimeZone.MiddleEastStandardTime ,"Middle East Standard Time"},
            {enTimeZone.EEuropeStandardTime ,"E. Europe Standard Time"},
            {enTimeZone.WestBankStandardTime ,"West Bank Standard Time"},
            {enTimeZone.SouthAfricaStandardTime ,"South Africa Standard Time"},
            {enTimeZone.SudanStandardTime ,"Sudan Standard Time"},
            {enTimeZone.FLEStandardTime ,"FLE Standard Time"},
            {enTimeZone.EgyptStandardTime ,"Egypt Standard Time"},
            {enTimeZone.KaliningradStandardTime,"Kaliningrad Standard Time"},
            {enTimeZone.IsraelStandardTime ,"Israel Standard Time"},
            {enTimeZone.LibyaStandardTime ,"Libya Standard Time"},
            {enTimeZone.NamibiaStandardTime ,"Namibia Standard Time"},
            {enTimeZone.SyriaStandardTime ,"Syria Standard Time"},
            {enTimeZone.ArabicStandardTime ,"Arabic Standard Time"},
            {enTimeZone.ArabStandardTime ,"Arab Standard Time"},
            {enTimeZone.BelarusStandardTime ,"Belarus Standard Time"},
            {enTimeZone.RussianStandardTime ,"Russian Standard Time"},
            {enTimeZone.EAfricaStandardTime ,"E. Africa Standard Time"},
            {enTimeZone.TurkeyStandardTime ,"Turkey Standard Time"},
            {enTimeZone.IranStandardTime ,"Iran Standard Time"},
            {enTimeZone.ArabianStandardTime ,"Arabian Standard Time"},
            {enTimeZone.AstrakhanStandardTime ,"Astrakhan Standard Time"},
            {enTimeZone.AzerbaijanStandardTime ,"Azerbaijan Standard Time"},
            {enTimeZone.CaucasusStandardTime ,"Caucasus Standard Time"},
            {enTimeZone.MauritiusStandardTime ,"Mauritius Standard Time"},
            {enTimeZone.SaratovStandardTime ,"Saratov Standard Time"},
            {enTimeZone.GeorgianStandardTime,"Georgian Standard Time"},
            {enTimeZone.VolgogradStandardTime ,"Volgograd Standard Time"},
            {enTimeZone.RussiaTimeZone3 ,"Russia Time Zone 3"},
            {enTimeZone.AfghanistanStandardTime,"Afghanistan Standard Time"},
            {enTimeZone.WestAsiaStandardTime,"West Asia Standard Time"},
            {enTimeZone.QyzylordaStandardTime ,"Qyzylorda Standard Time"},
            {enTimeZone.EkaterinburgStandardTime ,"Ekaterinburg Standard Time"},
            {enTimeZone.PakistanStandardTime,"Pakistan Standard Time"},
            {enTimeZone.IndiaStandardTime,"India Standard Time"},
            {enTimeZone.SriLankaStandardTime,"Sri Lanka Standard Time"},
            {enTimeZone.NepalStandardTime,"Nepal Standard Time"},
            {enTimeZone.CentralAsiaStandardTime ,"Central Asia Standard Time"},
            {enTimeZone.BangladeshStandardTime ,"Bangladesh Standard Time"},
            {enTimeZone.OmskStandardTime ,"Omsk Standard Time"},
            {enTimeZone.MyanmarStandardTime ,"Myanmar Standard Time"},
            {enTimeZone.SEAsiaStandardTime ,"SE Asia Standard Time"},
            {enTimeZone.AltaiStandardTime ,"Altai Standard Time"},
            {enTimeZone.WMongoliaStandardTime ,"W. Mongolia Standard Time"},
            {enTimeZone.NorthAsiaStandardTime ,"North Asia Standard Time"},
            {enTimeZone.NCentralAsiaStandardTime ,"N. Central Asia Standard Time"},
            {enTimeZone.TomskStandardTime ,"Tomsk Standard Time"},
            {enTimeZone.SingaporeStandardTime ,"Singapore Standard Time"},
            {enTimeZone.ChinaStandardTime ,"China Standard Time"},
            {enTimeZone.WAustraliaStandardTime ,"W. Australia Standard Time"},
            {enTimeZone.TaipeiStandardTime ,"Taipei Standard Time"},
            {enTimeZone.UlaanbaatarStandardTime ,"Ulaanbaatar Standard Time"},
            {enTimeZone.NorthAsiaEastStandardTime ,"North Asia East Standard Time"},
            {enTimeZone.AusCentralWStandardTime ,"Aus Central W. Standard Time"},
            {enTimeZone.TransbaikalStandardTime ,"Transbaikal Standard Time"},
            {enTimeZone.TokyoStandardTime ,"Tokyo Standard Time"},
            {enTimeZone.NorthKoreaStandardTime ,"North Korea Standard Time"},
            {enTimeZone.KoreaStandardTime ,"Korea Standard Time"},
            {enTimeZone.YakutskStandardTime ,"Yakutsk Standard Time"},
            {enTimeZone.CenAustraliaStandardTime ,"Cen. Australia Standard Time"},
            {enTimeZone.AUSCentralStandardTime ,"AUS Central Standard Time"},
            {enTimeZone.EAustraliaStandardTime,"E. Australia Standard Time"},
            {enTimeZone.WestPacificStandardTime ,"West Pacific Standard Time"},
            {enTimeZone.TasmaniaStandardTime ,"Tasmania Standard Time"},
            {enTimeZone.AUSEasternStandardTime ,"AUS Eastern Standard Time"},
            {enTimeZone.VladivostokStandardTime ,"Vladivostok Standard Time"},
            {enTimeZone.LordHoweStandardTime ,"Lord Howe Standard Time"},
            {enTimeZone.BougainvilleStandardTime ,"Bougainville Standard Time"},
            {enTimeZone.MagadanStandardTime ,"Magadan Standard Time"},
            {enTimeZone.NorfolkStandardTime ,"Norfolk Standard Time"},
            {enTimeZone.SakhalinStandardTime ,"Sakhalin Standard Time"},
            {enTimeZone.CentralPacificStandardTime ,"Central Pacific Standard Time"},
            {enTimeZone.RussiaTimeZone10 ,"Russia Time Zone 10"},
            {enTimeZone.RussiaTimeZone11 ,"Russia Time Zone 11"},
            {enTimeZone.NewZealandStandardTime ,"New Zealand Standard Time"},
            {enTimeZone.UTC12 ,"UTC+12"},
            {enTimeZone.FijiStandardTime ,"Fiji Standard Time"},
            {enTimeZone.KamchatkaStandardTime,"Kamchatka Standard Time"},
            {enTimeZone.ChathamIslandsStandardTime ,"Chatham Islands Standard Time"},
            {enTimeZone.UTC13 ,"UTC+13"},
            {enTimeZone.TongaStandardTime ,"Tonga Standard Time"},
            {enTimeZone.SamoaStandardTime ,"Samoa Standard Time"},
            {enTimeZone.LineIslandsStandardTime ,"Line Islands Standard Time"}
        };

        public static DateTime ToZoneLocalDate(this DateTime LocalDate,enTimeZone Zone)
        {
            TimeZoneInfo cstZone = TimeZoneInfo.FindSystemTimeZoneById(ZoneIdName[Zone]);
            DateTime utcTime = LocalDate.ToUniversalTime();
            return TimeZoneInfo.ConvertTimeFromUtc(utcTime, cstZone);
        }
    }
}
